name: note
description: "A new Flutter project."


publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  gap: ^3.0.1
  go_router: ^15.1.2
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flutter_screenutil: ^5.9.3
  flutter_quill: ^11.4.1
  google_fonts: ^4.0.4
  lottie: ^3.0.0
  loading_animation_widget: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


  fonts:
    - family: 'ferdoka'
      fonts:
        - asset: assets/fonts/ferdoka.ttf
          weight: 400

    - family: 'serif'
      fonts:
        - asset: assets/fonts/AncizarSerif.ttf
          weight: 900



  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
